### PR TITLE
WIP (Issues #40, #41) Add basic (single/multiple) drag and drop features to client-react package

### PR DESCRIPTION
**Pull request by Mengsuper**
New Feature Submissions
---

Drag-and-drop is a common feature for file management. So it's nice to include them. 
 
Release notes
---

Add new drag and drop features, include single or multiple drag and drop

### CODE REVIEW

**Comment by kvolkovich-sc** [comment]
Hello, @Mengsuper.

Very thanks for PR! Its really useful feature.

As I understand, you have added dnd for UI part, but to finish this task, we still need to implement API calls.

```
// make api call if necessary
```

Also we don't need to move item if nothing been happened.

If you move file => file, directory => file, etc.  

I'll take more detailed look at this weekend.

:+1:

**Comment by Mengsuper** [comment]
Hi, @kvolkovich-sc, you're right. I only implement the UI part supporting rearranging items.

**Comment by Mengsuper** [comment]
Hi, @kvolkovich-sc, you're right. I only implement the UI part supporting rearranging items, which doesn't require api call. I will work on the drag and drop file/dir into dir and also the api calls. 
BTW, do you know whether I can customize the resource object in my connector (such as adding an display order property which can be used to keep track of the order of items)? Thank you.

**Comment by kvolkovich-sc** [comment]
If I understand you right, you can modify this line:

https://github.com/OpusCapita/filemanager/blob/c95666a7a2210e18ec80bb66126a68bd83296fc3/packages/client-react/src/client/components/FileNavigator/FileNavigator.react.js#L208

Something like:

```js
const resourceChildren = (await this.getChildrenForId(resource.id, sortBy, sortDirection))
	.map((child, i) => ({ ...child, _dndOriginalIndex: i }));
```

If it will work, we'll can think how to avoid it if possible.

**Comment by Mengsuper** [comment]
I don't think it will work if we want to keep the order of each file/dir. For current project, the default order is sorting by 'ASC name'. But if users drag and drop file/dir around, we may need keep track of their changes. And keep this order as the default. So we may add another attribute to the resource object.

**Comment by kvolkovich-sc** [comment]
Maybe it I don't fully understand what we want to track.

I propose something like it:

- User drop file on directory
- Initiate API call `move a to b`
- Mark `a` as hidden on UI by adding `a.id` to `hiddenResourceChildren` array in `FileNavigator`'s state.
- If `move a to b` API call response finished with success
   	- Show notification `a to b moved successfully`
	- If user still in same directory, request new state of directory
	- Unmark `a` as hidden on UI
- If `move a to b` API call response finished with fail
   	- Show notification `a to b move failed`
	- If user still in same directory, request new state of directory
	- Unmark `a` as hidden on UI
	
Do you see some issues in such approach?

**Comment by Mengsuper** [comment]
Thanks for clarification. I have been thinking one more feature on top of it.

**Comment by kvolkovich-sc** [comment]
@Mengsuper, what exactly?

**Comment by Mengsuper** [comment]
I'm working on a project which requires the server to record the order of items(file/dir). Users can just drag and drop them to change the order (it may not matter for your project). At the same time, it supports the drag and drop items into dir/folder (as you described above).

**Comment by kvolkovich-sc** [comment]
Hm.

Its can be interesting. 

I have an idea of transform **Filemanager** to **Hierarchical resources manager** (any type of resources) in future. But it just a thoughts now.

If you will continue work, can you please ping me if you got something workable (via new issue/PR/email)?

**Comment by Mengsuper** [comment]
Interesting idea. Sure. I would like to spend some time working on it.

**Pull request closed without merging**
