### PR TITLE
(#29) Add variables' replacement into translations

### PR DESCRIPTION
**Pull request by abaliunov-sc**
#29 

### New Feature Submissions

Add variables' replacement into translations.
The list of arguments of the **getMessage** function has been changed.
Now **getMessage**  can be invoked with three arguments **getMessage(locale, key, params)**:

* **locale**,
* **key**,
* **params** - (optional) the object containing parameters which will be substituted in the translation

#### Example:

**translation.js**
```
const translations = {
  en: {

    // ...

    fileExist: 'File or folder with name {name} already exists',

    // ...

  }
};
```

**create-folder.js**
```
import getMessagefrom '../../translations';

// ...

let mess = getMessage('en', 'fileExist', { name: 'New name' }); // File or folder with name New name already exists

// ...
```

Release notes
---

(#29) Added `en` and `de` locales for `connector-google-drive-v2` and `connector-node-v1`

### CODE REVIEW

**Comment by kvolkovich-sc** [comment]
@abaliunov-sc, can you please add these translations?

In case of any questions contact to @apolishchuk-sc 

```
const translations = {
en: {
   uploading: 'Uploading',
   upload: 'Upload',
   remove: 'Remove',
   download: 'Download',
   rename: 'Rename',
   creating: 'Creating',
   create: 'Create',
   createFolder: 'Create folder',
   zipping: 'Zipping',
   items: 'items',
   item: 'item',
   cancel: 'Cancel',
   confirm: 'Confirm',
   folderName: 'Folder name',
   files: 'files',
   // TODO - add substitutions instead of splitting message in two parts
   fileExist1: 'File or folder with name',
   fileExist2: 'already exists',
   newName: 'New name',
   emptyName: 'Name can\'t be empty',
   tooLongFolderName: 'Folder name can\'t contain more than 255 characters',
   folderNameNotAllowedCharacters: 'Folder name contains not allowed characters',
   title: 'Title',
   fileSize: 'File size',
   lastModified: 'Last modified',
   reallyRemove: ' will be deleted. Do you really want to proceed?',
   unableReadDir: 'Unable to read a directory.'
       },
 de: {
   uploading: 'Wird hochgeladen',
   upload: 'Hochladen’,
   remove: 'Löschen’,
   download: 'Herunterladen',
   rename: 'Umbenennen',
   creating: 'Wird erstellt',
   create: 'Erstellen',
   createFolder: 'Verzeichnis erstellen',
   zipping: 'Zippen',
   items: 'Elemente',
   item: 'Element',
   cancel: 'Stornieren',
   confirm: 'Bestätigen',
   folderName: ' Verzeichnisname',
   files: 'Dateien',
   // TODO - add substitutions instead of splitting message in two parts
   fileExist1: 'Die Datei oder Verzeichnis mit dem Namen',
   fileExist2: 'existiert bereits',
   newName: 'Neuer Name',
   emptyName: 'Der Name darf nicht leer sein',
   tooLongFolderName: 'Der Verzeichnisname darf nicht mehr als 255 Symbole enthalten',
   folderNameNotAllowedCharacters: 'Das Verzeichnisname enthält nicht erlaubte Zeichen',
           title: 'Titel',
   fileSize: 'Dateigröße',
   lastModified: 'Zuletzt geändert',
   reallyRemove: ' wird/werden gelöscht. Möchten Sie wirklich fortfahren?',
   unableReadDir: 'Ein Directory kann nicht gelesen werden.'
 }
};
```

**Comment by kvolkovich-sc** [comment]
@abaliunov-sc, please add these translations for "Move back", "Move forward" toolbar buttons

```
Move forward = Vorwärts
Move back = Zurück
```

**Comment by abaliunov-sc** [comment]
Done

**Comment by abaliunov-sc** [comment]
Add translations:
```
  en: {
    creatingName: 'Creating {name}...',
    downloadingItem: 'Downloading 1 item',
    downloadingItems: 'Downloading {quantity} items',
    downloadingName: 'Downloading {name}...',
    error: 'error',
    fileExist: 'File or folder with name {name} already exists',
    notAllowedCharacters: 'Name contains not allowed characters',
    notInitAPIClient: 'Google API client cannot be initialized',
    signInFail: 'Google Drive sign-in failed',
    signInSuccess: 'Google Drive sign-in was successful',
    successInit: 'Google API client successfully initialized',
    tooLongName: 'Name can\'t contain more than 255 characters',
    uploadingItem: 'Uploading 1 item',
    uploadingItems: 'Uploading {quantity} items',
    zippingItem: 'Zipping 1 item',
    zippingItems: 'Zipping {quantity} items',
  },

  de: {
    creatingName: '{name} wird angelegt...',
    downloadingItem: '1 Element wird hochgeladen',
    downloadingItems: '{quantity} Elemente werden hochgeladen',
    downloadingName: '{name} wird hochgeladen...',
    error: 'Fehler',
    fileExist: 'Die Datei oder Verzeichnis mit dem Namen {name} existiert bereits',
    notAllowedCharacters: 'Der Name des Verzeichnisses enthält nicht erlaubte Zeichen',
    notInitAPIClient: 'Google API-Client konnte nicht initialisiert werden',
    signInFail: 'Google Drive-Anmeldung fehlgeschlagen',
    signInSuccess: 'Google Drive-Anmeldung erfolgreich',
    successInit: 'Google API-Client wurde erfolgreich initialisiert',
    tooLongName: 'Der Verzeichnisname darf nicht mehr als 255 Symbole enthalten',
    uploadingItem: '1 Element wird geladen',
    uploadingItems: '{quantity} Elemente werden geladen',
    zippingItem: '1 Element wird gezippt',
    zippingItems: '{quantity} Elemente werden gezippt',
  },
```

**Pull request merged**
